# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: adf6ddfc1746612ac712e33aaadf7fc39ba3c22645b3956c026c1d414074c5f3f17b367be385a5a4bf42c6384524cc712d297d63b0f5d423e5d8704c162a7c50

test:
  secret_key_base: 96b3a0307c985ef497b2fb0cc460c83d70ef11b8e80d9a17421d1d80d358f0894df98d3c0be386b6538b544d593b036b6ee556106c3049cf014c88a0f93de873

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
