# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3f2964420b4684d3b31f5c8d8ea7af73c28e73fb640f20b9818a8d3df07b2638f16ba75ca10699160423587f7674b51693c482b165f7e034481e170520c5647a

test:
  secret_key_base: 4e1d5a9b17258524283b8b8be827c9ba3305a6efecd6616aee7e9c7cfa92e681f9c459f3d774afa2ee1a0e56236d9912d92cb5c932adff3727e38947f4260063

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
